language: node_js
node_js:
  - "v12.6.0"
cache:
  directories:
    - "node_modules"
script:
  - npm test
after_success:
  - npm run report-coverage
notifications:
    slack: g-explorer:81CbfYw9kEml7k1QcXQkGfrB
